# https://circleci.com/docs/2.0/language-android/#sample-configuration
# https://github.com/shadowsocks/shadowsocks-android/blob/master/.circleci/config.yml

# root@f199f32871af:~# df -h
# Filesystem      Size  Used Avail Use% Mounted on
# none            826G  272G  554G  33% /
# tmpfs            64M     0   64M   0% /dev
# tmpfs            35G     0   35G   0% /sys/fs/cgroup
# /dev/nvme1n1p1  9.7G  2.5G  7.3G  26% /dev/init
# /dev/nvme0n1    826G  272G  554G  33% /etc/hosts
# shm              30G     0   30G   0% /dev/shm
# udev             35G     0   35G   0% /dev/tty
# tmpfs            35G     0   35G   0% /proc/acpi
# tmpfs            35G     0   35G   0% /proc/scsi
# tmpfs            35G     0   35G   0% /sys/firmware

version: 2
jobs:
  build:
    # https://circleci.com/docs/2.0/configuration-reference/#environment
    # environment:
    #   L:  'https://'
    #   H:  'ffffffffffffffffffffffffffffffff'
    #   F:  'xxx.7z'
    #   C:  'xxxsum.txt'
    working_directory: ~/code
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      # https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/android/images
      # https://en.wikipedia.org/wiki/Debian_version_history
      # https://wiki.ubuntu.com/Releases
      # - image: ubuntu:hirsute # 21.04 # https://stackoverflow.com/q/66319610
      - image: ubuntu:focal     # 20.04.2 LTS
    resource_class: medium
    steps:
      # - run:
      #     name: Stop for SSH
      #     command: |
      #       false
      - run:
          name: Prepare
          command: |
            apt update
            apt install -y curl wget
      - run:
          name: Download
          command: |
            lsb_release -a
            cd ~
            # https://superuser.com/questions/426877
            # https://addons.mozilla.org/en-US/firefox/search/?q=wget
            # https://addons.mozilla.org/en-US/firefox/addon/cliget
            # curl/wget ... --cookie '...' ... --output 'Final Fantasy X (Japan).7z'
            curl --header 'Host: files.romspure.com' --user-agent 'Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://romsforever.co/' --cookie 'cf_chl_2=3d13706088c25c0; cf_chl_prog=x9; cf_clearance=b33d5809f54352a08cd72713e758814cbe9769cc-1623601281-0-150' --header 'Upgrade-Insecure-Requests: 1' 'https://files.romspure.com/PS2/NTSC-Asia/Final%20Fantasy%20X%20%28Japan%29.7z?token=' --output 'Final Fantasy X (Japan).7z'
      - run:
          name: Split
          command: |
            cd ~
            mkdir split
            cd split
            split --verbose -b $((1024*1024*1024)) ~/'Final Fantasy X (Japan).7z'
            ls -l
            ls -lh
      - run:
          name: Checksum
          command: |
            cd ~/split
            sha1sum * | tee sha1sum.txt
            sha1sum ../'Final Fantasy X (Japan).7z' | tee -a sha1sum.txt
            # cat sha1sum.txt | tr -s ' ' >"sha1sum.txt".onespace
          # no_output_timeout: 30m
          # no_output_timeout: 1.5h
      - store_artifacts:
          # https://circleci.com/docs/2.0/artifacts/#artifacts-overview
          path: ~/split/
          destination: split