# https://circleci.com/docs/2.0/language-android/#sample-configuration
# https://github.com/shadowsocks/shadowsocks-android/blob/master/.circleci/config.yml

# root@f199f32871af:~# df -h
# Filesystem      Size  Used Avail Use% Mounted on
# none            826G  272G  554G  33% /
# tmpfs            64M     0   64M   0% /dev
# tmpfs            35G     0   35G   0% /sys/fs/cgroup
# /dev/nvme1n1p1  9.7G  2.5G  7.3G  26% /dev/init
# /dev/nvme0n1    826G  272G  554G  33% /etc/hosts
# shm              30G     0   30G   0% /dev/shm
# udev             35G     0   35G   0% /dev/tty
# tmpfs            35G     0   35G   0% /proc/acpi
# tmpfs            35G     0   35G   0% /proc/scsi
# tmpfs            35G     0   35G   0% /sys/firmware

version: 2
jobs:
  build:
    # https://circleci.com/docs/2.0/configuration-reference/#environment
    environment:
      L:  'https://xilinx-ax-dl.entitlenow.com/dl/ul/2019/11/08/R210260632/Xilinx_Vivado_2019.2_1106_2127.tar.gz/e8553466042cb8b9dcd2795aafd3637f/5DD6EFA6?akdm=0&filename=Xilinx_Vivado_2019.2_1106_2127.tar.gz'
      H:  'e2b2762964ef5f014591b13d77d823ab'
      F:  'vivado.tar.gz'
      C:  'md5.txt'
    working_directory: ~/code
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      # https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/android/images
      # https://en.wikipedia.org/wiki/Debian_version_history
      - image: ubuntu:disco
    resource_class: medium
    steps:
      # - run:
      #     name: Stop for SSH
      #     command: |
      #       false
      - run:
          name: Prepare
          command: |
            apt update
            apt install -y wget
      - run:
          name: Download
          command: |
            cd ~
            wget -O $F "$L"
      - run:
          name: Split
          command: |
            cd ~
            mkdir split
            cd split
            split --verbose -b $((1024*1024*1024)) ~/$F
            ls -l
            ls -lh
      - run:
          name: Checksum
          command: |
            cd ~/split
            touch $C
            echo "$H  https://www.xilinx.com/support/download.html" | tee -a $C
            md5sum ../$F | tee -a $C
            md5sum x* | tee -a $C
          # no_output_timeout: 30m
          # no_output_timeout: 1.5h
      - store_artifacts:
          # https://circleci.com/docs/2.0/artifacts/#artifacts-overview
          path: ~/split/
          destination: split